services:
  nginx:
    container_name: nginx
    build:
      context: ./service/nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        TZ: ${TZ}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${NGINX_SSL_CERTIFICATE_DIR}:/ssl
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf
      - ${NGINX_FASTCGI_PHP_CONF}:/etc/nginx/fastcgi-php.conf
      - ${NGINX_FASTCGI_PARAMS}:/etc/nginx/fastcgi_params
      - ${NGINX_LOG_DIR}:/var/log/nginx
    restart: always
    networks:
      - default

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${DATA_DIR}/redis:/data/:rw
    restart: always
    entrypoint: [
      "redis-server",
      "/etc/redis.conf",
      "--requirepass",
      "${REDIS_PASSWORD}"
    ]
    environment:
      TZ: ${TZ}
    networks:
      - default

  mysql5:
    # 指定使用 amd64 平台,mac芯片m1-m4需要打开
    platform: linux/amd64
    container_name: mysql5
    image: mysql:${MYSQL5_VERSION}
    ports:
      - "${MYSQL5_HOST_PORT}:3306"
    volumes:
      - ${MYSQL5_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DATA_DIR}/mysql5:/var/lib/mysql/:rw
      - ${MYSQL5_LOG_DIR}:/var/log/mysql/:rw

    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL5_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL5_ROOT_HOST}
      TZ: ${TZ}

  mysql8:
    image: mysql:${MYSQL8_VERSION}
    container_name: mysql8
    ports:
      - "${MYSQL8_HOST_PORT}:3306"
    volumes:
      - ${MYSQL8_CONF_FILE}:/etc/mysql8/conf.d/mysql.cnf:ro
      - ${DATA_DIR}/mysql8:/var/lib/mysql/:rw
      - ${MYSQL8_LOG_DIR}:/var/log/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL8_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL8_ROOT_HOST}
      TZ: ${TZ}

  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./service/rabbitmq
      args:
        RABBITMQ_VERSION: ${RABBITMQ_VERSION}
        RABBITMQ_PLUGINS: ${RABBITMQ_PLUGINS}
    restart: always
    ports:
      - "${RABBITMQ_HOST_PORT_C}:5672"
      - "${RABBITMQ_HOST_PORT_S}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      TZ: ${TZ}
    networks:
      - default

  php82:
    container_name: php82
    build:
      context: ./service/php82
      args:
        PHP_VERSION: ${PHP82_VERSION}
        PHP_EXTENSIONS: ${PHP82_EXTENSIONS}
        DEBIAN_MIRROR_DOMAIN: deb.debian.org
        TZ: ${TZ}
    expose:
      - 9500-9599 # 暴露容器内部端口段（可选，用于文档说明）
    ports:
      - "9500-9599:9500-9599" # 端口段映射
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP82_PHP_CONF_FILE}:/usr/local/etc/php/php.ini
      - ${PHP82_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf
      - ${PHP82_LOG_DIR}:/var/log/php
      - ${PHP82_DATA_COMPOSER}:/tmp/composer
    restart: always
    privileged: true # 添加privileged模式 特权模式
    cap_add:
      - SYS_PTRACE
    networks:
      - default

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      # 解除下面的注释可以设置网段，用于nginx等容器固定容器IP
      #config:
      #  - subnet: 10.0.0.0/24
